// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK9I6AmoB5X77R_NQcZeTWOr2oABj_qlk',
    appId: '1:375929819946:web:0d44f4376cfd1c25e50453',
    messagingSenderId: '375929819946',
    projectId: 'medi-navi2025',
    authDomain: 'medi-navi2025.firebaseapp.com',
    storageBucket: 'medi-navi2025.firebasestorage.app',
    measurementId: 'G-QMVR4GM6QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lhTnMFhjSZEG9bL9IJjCpWxg_H8XBUA',
    appId: '1:375929819946:android:71b75982b8864b53e50453',
    messagingSenderId: '375929819946',
    projectId: 'medi-navi2025',
    storageBucket: 'medi-navi2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQ0VKOz_awug5ThXhvIMm19f0esf7w8A',
    appId: '1:375929819946:ios:7f22ade50ff43340e50453',
    messagingSenderId: '375929819946',
    projectId: 'medi-navi2025',
    storageBucket: 'medi-navi2025.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQ0VKOz_awug5ThXhvIMm19f0esf7w8A',
    appId: '1:375929819946:ios:7f22ade50ff43340e50453',
    messagingSenderId: '375929819946',
    projectId: 'medi-navi2025',
    storageBucket: 'medi-navi2025.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK9I6AmoB5X77R_NQcZeTWOr2oABj_qlk',
    appId: '1:375929819946:web:e2c35dc010905d28e50453',
    messagingSenderId: '375929819946',
    projectId: 'medi-navi2025',
    authDomain: 'medi-navi2025.firebaseapp.com',
    storageBucket: 'medi-navi2025.firebasestorage.app',
    measurementId: 'G-4LE1QSBXV0',
  );

}